<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>

    <ApplicationIcon>..\NzbDrone.Host\Releasarr.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="!$(RuntimeIdentifier.StartsWith('win'))">
    <AssemblyName>Releasarr</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Host\Releasarr.Host.csproj" />
  </ItemGroup>
</Project>
