<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NBuilder" Version="6.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Core\Releasarr.Core.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Releasarr.Test.Common.csproj" />
    <ProjectReference Include="..\Releasarr.Http\Releasarr.Http.csproj" />
  </ItemGroup>
</Project>
