// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'contentType': string;
  'date': string;
  'status': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
