<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Releasarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Releasarr.Test.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Windows\Releasarr.Windows.csproj" />
  </ItemGroup>
</Project>
