<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Host\Releasarr.Host.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Releasarr.Test.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Dummy\Releasarr.Test.Dummy.csproj" />
  </ItemGroup>
</Project>
